### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by michielbdejong** [NoelDeMartin/solid-focus#13]
I'm working out how I can build this code. I'm using GitPod for this.

So far I found:
```
nvm install 10
nvm use 10
PYTHON=python2 npm install @vue/cli-service
```

**Comment by NoelDeMartin** [comment]
Hey, thanks for opening an issue.

I've started working on a new version of the app rebuilding it from scratch, so I'm not going to spend much time fixing or improving the current version. You can read more about it in #10.

However, I guess you want to run it locally for testing the migration using the [data modules](https://github.com/solid-contrib/data-modules). So I'm fine with helping you get it running if you're facing any issues :). I tried to build the app again in my local machine, and it turns out it was using node 8, not 10 :sweat_smile:. I've added an `.nvmrc` file so that should be helpful for anyone else who wants to build it as well. I also tried in `github.dev` and it works, so it should be the same for gitpod.
