### ISSUE TITLE
can't login to solid focus

### ISSUE THREAD

**Issue by scenaristeur** [NoelDeMartin/solid-focus#8]
looking for soukai, i wanted to log to solid Focus but clicking on "Login with Solid" does not open the login popup and i got an error in js console

![image](https://user-images.githubusercontent.com/4020744/71314424-81ac0100-2448-11ea-8d0e-7b44567da1eb.png)

**Comment by NoelDeMartin** [comment]
Looking at the screenshot, it seems like you didn't write the url. The input with the "Solid POD" placeholder should be filled with the url to your POD.

Maybe you were expecting this to open the login popup. But I am not doing that on purpose, because I didn't like the idea of "suggesting" some domains, in my opinion that goes against the idea of decentralization.

I guess I could do a better job at communicating this error, so I'll keep this issue open as a usability improvement.

**Comment by scenaristeur** [comment]
ok, that's all my fault, that's right, i was expecting the popup
